name: Build Kernel

permissions:
  contents: write
  actions: write

on:
  workflow_call:

jobs:
  # OPPO
  ## Oneplus
  Oneplus-Kona-Tropsi-X-Kernel-Build:
    name: "Build Oneplus 8 Series (OxygenOS 14 A14)"
    strategy:
      fail-fast: true
    uses: ./.github/workflows/Oneplus-Kona-Tropsi-X-Kernel-Build.yml
    secrets: inherit
